[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "urban vehicle cereal garage entry tray life basket clever confirm collect maple pyramid frequent trash valley shine slot rural task ice also special venture"
